// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIABJ6K7Nny_IjZPNBlo4tWG6DgoyHX1A',
    appId: '1:548628431489:web:6a3ee08a758635924e4380',
    messagingSenderId: '548628431489',
    projectId: 'chatapp-80eb6',
    authDomain: 'chatapp-80eb6.firebaseapp.com',
    storageBucket: 'chatapp-80eb6.firebasestorage.app',
    measurementId: 'G-MQXEMQLWS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa6OGOOTQ0ng3ovpLZANQUqGkqtZRQkwQ',
    appId: '1:548628431489:android:95d6b3b065f21d2a4e4380',
    messagingSenderId: '548628431489',
    projectId: 'chatapp-80eb6',
    storageBucket: 'chatapp-80eb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwsc7RX5EBg6GCTszGryczguuLUTJtSs8',
    appId: '1:548628431489:ios:9398497b6aa1ecb24e4380',
    messagingSenderId: '548628431489',
    projectId: 'chatapp-80eb6',
    storageBucket: 'chatapp-80eb6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwsc7RX5EBg6GCTszGryczguuLUTJtSs8',
    appId: '1:548628431489:ios:9398497b6aa1ecb24e4380',
    messagingSenderId: '548628431489',
    projectId: 'chatapp-80eb6',
    storageBucket: 'chatapp-80eb6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIABJ6K7Nny_IjZPNBlo4tWG6DgoyHX1A',
    appId: '1:548628431489:web:a8a854002ccd33c34e4380',
    messagingSenderId: '548628431489',
    projectId: 'chatapp-80eb6',
    authDomain: 'chatapp-80eb6.firebaseapp.com',
    storageBucket: 'chatapp-80eb6.firebasestorage.app',
    measurementId: 'G-71T39G2B6M',
  );

}